import json
import itertools
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# MATRIZ DE VANTAGENS (SEM TETO DE PONTOS - MATEMÁTICA ACUMULATIVA)
MATRIZ_VANTAGENS = {
    "anti_cc": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 35, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 15, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 40, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "anti_dash": {"anti_cc": 0, "anti_dash": 0, "assassino": 15, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 35, "desengaje": 0, "engaje": 15, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 30, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "assassino": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 10, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 40, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 25, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "blink_teletransporte": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 25, "cura": 0, "curto": 15, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 15, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 20, "provocacao_taunt": 10, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "bloqueio_projetil": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 10, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 15, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 25, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 35, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 20},
    "camuflagem": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 25, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 30, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 15, "lutador": 0, "medio": 0, "mobilidade": 15, "poke": 25, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "CC": {"anti_cc": 0, "anti_dash": 0, "assassino": 35, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 10, "curto": 15, "dano_ataque": 0, "dano_explosivo": 15, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 25, "desengaje": 0, "engaje": 20, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 20, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 20, "medio": 0, "mobilidade": 35, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 10, "tank_resistencia_magica": 10, "tank_vida": 10, "team_fight": 0, "velocidade_ataque": 0},
    "controle_zona": {"anti_cc": 0, "anti_dash": 0, "assassino": 15, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 25, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 15, "desengaje": 0, "engaje": 25, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 20, "medio": 0, "mobilidade": 10, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "cura": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 10, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 10, "dano_vida_maxima": 20, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 30, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 10, "team_fight": 0, "velocidade_ataque": 0},
    "curto": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "dano_ataque": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 10, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 15, "tank_vida": 15, "team_fight": 0, "velocidade_ataque": 0},
    "dano_explosivo": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 25, "curto": 0, "dano_ataque": 10, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 40, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "dano_fisico": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 10, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 5, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 30, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "dano_magico": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 15, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 10, "shild": 0, "tank_armadura": 30, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "dano_verdadeiro": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 15, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 40, "tank_resistencia_magica": 40, "tank_vida": 20, "team_fight": 0, "velocidade_ataque": 0},
    "dano_vida_maxima": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 20, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 15, "tank_resistencia_magica": 15, "tank_vida": 40, "team_fight": 0, "velocidade_ataque": 0},
    "dash_avanco": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 10, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 15, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 20, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 20, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "desengaje": {"anti_cc": 0, "anti_dash": 0, "assassino": 20, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 20, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 15, "desengaje": 0, "engaje": 40, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 10, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 25, "velocidade_ataque": 0},
    "engaje": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 10, "cura": 15, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 20, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 20, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 30, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "escudo_de_feitico": {"anti_cc": 0, "anti_dash": 0, "assassino": 15, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 40, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 15, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 25, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 20, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 20, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "evasao_ataque_basico": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 45, "dano_explosivo": 0, "dano_fisico": 20, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 10, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 45},
    "execucao": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 30, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 10, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 25, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 20, "team_fight": 0, "velocidade_ataque": 0},
    "fragil": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "global_semiglobal": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 15, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 10, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 25, "velocidade_ataque": 0},
    "imortalidade": {"anti_cc": 0, "anti_dash": 0, "assassino": 35, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 10, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 40, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 20, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 40, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "inalvejavel": {"anti_cc": 0, "anti_dash": 0, "assassino": 20, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 25, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 35, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 20, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 10, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "invisibilidade_verdadeira": {"anti_cc": 0, "anti_dash": 0, "assassino": 20, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 30, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 35, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 10, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 15, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "lentidao_pesada": {"anti_cc": 0, "anti_dash": 0, "assassino": 10, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 20, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 15, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 25, "medio": 0, "mobilidade": 25, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "longo": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 25, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 20, "medio": 15, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 10, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "lutador": {"anti_cc": 0, "anti_dash": 0, "assassino": 35, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 20, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 15, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "medio": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 20, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "mobilidade": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 20, "cura": 0, "curto": 15, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 15, "medio": 0, "mobilidade": 0, "poke": 25, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "poke": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 25, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 10, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 25, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 15, "tank_resistencia_magica": 15, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "provocacao_taunt": {"anti_cc": 0, "anti_dash": 0, "assassino": 40, "blink_teletransporte": 35, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 30, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 10, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 40, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "reduz_armadura": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 20, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 40, "tank_resistencia_magica": 0, "tank_vida": 10, "team_fight": 0, "velocidade_ataque": 0},
    "shild": {"anti_cc": 0, "anti_dash": 0, "assassino": 20, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 35, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 10, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 25, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "tank_armadura": {"anti_cc": 0, "anti_dash": 0, "assassino": 25, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 35, "dano_explosivo": 0, "dano_fisico": 40, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 10, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 30},
    "tank_resistencia_magica": {"anti_cc": 0, "anti_dash": 0, "assassino": 20, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 40, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 10, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "tank_vida": {"anti_cc": 0, "anti_dash": 0, "assassino": 30, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 40, "dano_fisico": 0, "dano_magico": 15, "dano_verdadeiro": 10, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "team_fight": {"anti_cc": 0, "anti_dash": 0, "assassino": 30, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 10, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 15, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 0, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 0, "tank_resistencia_magica": 0, "tank_vida": 0, "team_fight": 0, "velocidade_ataque": 0},
    "velocidade_ataque": {"anti_cc": 0, "anti_dash": 0, "assassino": 0, "blink_teletransporte": 0, "bloqueio_projetil": 0, "camuflagem": 0, "CC": 0, "controle_zona": 0, "cura": 0, "curto": 0, "dano_ataque": 0, "dano_explosivo": 0, "dano_fisico": 0, "dano_magico": 0, "dano_verdadeiro": 0, "dano_vida_maxima": 0, "dash_avanco": 0, "desengaje": 0, "engaje": 0, "escudo_de_feitico": 0, "evasao_ataque_basico": 0, "execucao": 0, "fragil": 0, "global_semiglobal": 0, "imortalidade": 0, "inalvejavel": 0, "invisibilidade_verdadeira": 0, "lentidao_pesada": 0, "longo": 0, "lutador": 10, "medio": 0, "mobilidade": 0, "poke": 0, "provocacao_taunt": 0, "reduz_armadura": 0, "shild": 0, "tank_armadura": 5, "tank_resistencia_magica": 15, "tank_vida": 25, "team_fight": 0, "velocidade_ataque": 0}
}

def carregar_json(nome_arquivo):
    caminho = os.path.join(BASE_DIR, "data", nome_arquivo)
    if os.path.exists(caminho):
        with open(caminho, 'r', encoding='utf-8') as f:
            return json.load(f)
    return {}

def extrair_todas_tags(nome, stats, tags_json):
    dados_campeao = stats.get(nome, {})
    tags_extras = tags_json.get(nome, {}).get("tags", [])
    
    lista_completa = []
    if "dano" in dados_campeao: lista_completa.extend(dados_campeao["dano"])
    if "traits" in dados_campeao: lista_completa.extend(dados_campeao["traits"])
    if "range" in dados_campeao: lista_completa.append(dados_campeao["range"])
    lista_completa.extend(tags_extras)
    
    return set([str(t).lower().strip() for t in lista_completa])

def main():
    CHAMPION_STATS = carregar_json("campeoes.json")
    CHAMPION_TAGS = carregar_json("campeoes_tag.json")
    
    if not CHAMPION_STATS: return

    campeoes = [c for c in CHAMPION_STATS.keys() if c.lower() != "fraquezas"]
    matchups_finais = {}

    for campA, campB in itertools.combinations(campeoes, 2):
        tags_A = extrair_todas_tags(campA, CHAMPION_STATS, CHAMPION_TAGS)
        tags_B = extrair_todas_tags(campB, CHAMPION_STATS, CHAMPION_TAGS)
        
        pontos_A = 0
        pontos_B = 0
        
        for tag_atacante in tags_A:
            if tag_atacante in MATRIZ_VANTAGENS:
                for tag_defensor in tags_B:
                    if tag_defensor in MATRIZ_VANTAGENS[tag_atacante]:
                        pontos_A += MATRIZ_VANTAGENS[tag_atacante][tag_defensor]
                        
        for tag_atacante in tags_B:
            if tag_atacante in MATRIZ_VANTAGENS:
                for tag_defensor in tags_A:
                    if tag_defensor in MATRIZ_VANTAGENS[tag_atacante]:
                        pontos_B += MATRIZ_VANTAGENS[tag_atacante][tag_defensor]

        score_final = pontos_A - pontos_B

        if score_final != 0:
            chave = f"{campA}|{campB}"
            matchups_finais[chave] = int(score_final)

    caminho_saida = os.path.join(BASE_DIR, "data", "matchups.json")
    os.makedirs(os.path.dirname(caminho_saida), exist_ok=True)
    with open(caminho_saida, "w", encoding="utf-8") as f:
        json.dump(matchups_finais, f, indent=4, ensure_ascii=False)

if __name__ == "__main__":
    main()